- name: Install Nginx
  ansible.builtin.apt: 
    name: nginx
    state: present

- name: Copy conf for nginx
  ansible.builtin.template:
    dest: /etc/nginx/sites-enabled/default
    src: default.j2
  notify: Restart nginx