- name: make dir for apt key
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add InfluxData GPG key
  apt_key:
    url: https://repos.influxdata.com/influxdata-archive_compat.key
    state: present
    
- name: InfluxData APT repository
  apt_repository:
    repo: 'deb https://repos.influxdata.com/debian stable main'
    state: present
    update_cache: yes

- name: Download InfluxDB 1.8.10 deb
  get_url:
    url: https://dl.influxdata.com/influxdb/releases/influxdb_1.8.10_amd64.deb
    dest: /usr/local/bin/influxdb_1.8.10_amd64.deb

- name: Install InfluxDB
  apt:
    deb: /usr/local/bin/influxdb_1.8.10_amd64.deb
    update_cache: yes

- name: Influxdb Conf Template
  ansible.builtin.template:
    src: influxdb.conf.j2
    dest: /etc/influxdb/influxdb.conf
    mode: '0644'
  notify: Restart influxdb

- name: Install Telegraf
  apt:
    name: telegraf
    state: present

- name: Telegraf configuration file
  ansible.builtin.template:
    src: telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
  notify: Restart telegraf

- name: Start Telegraf
  service:
    name: telegraf
    state: started
    enabled: true  # start on boot 

- name: Start InfluxDB
  service:
    name: influxdb
    state: started
    enabled: true  # start on boot 

- name: Install Prometheus InfluxDB exporter
  get_url:
    url: https://github.com/carlpett/influxdb_stats_exporter/releases/download/v0.1.1/influx_stats_exporter_linux_amd64
    dest: /usr/local/bin/influxdb_stats_exporter
    mode: '0500'
    owner: prometheus 
  notify: Reload systemd
  
- name: Influxdb-stats exporter template
  ansible.builtin.template:
    src: prometheus-influxdb-stats-exporter.service.j2
    dest: /etc/systemd/system/prometheus-influxdb-stats-exporter.service
  notify: Reload systemd

- name: Make sure exporter is running
  ansible.builtin.service:
    name: prometheus-influxdb-stats-exporter
    state: started
    enabled: true

- name: Influx dir with owner
  ansible.builtin.file:
    path: /home/backup/influxdb
    state: directory
    mode: '0700'
    owner: backup

- name: InfluxDB backup
  template:
    src: influxdb_backup.conf.j2
    dest: /etc/cron.d/influx-backup
