- name: APT key dir
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Grafana rep key
  ansible.builtin.get_url:
    url: https://apt.grafana.com/gpg.key
    dest: /etc/apt/keyrings/grafana.asc
    mode: '0644'

- name: Grafana rep
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/grafana.asc] https://apt.grafana.com/ stable main"
    state: present
    update_cache: true

- name: install grafana
  ansible.builtin.apt:
    name: grafana
    state: present

- name: Grafana is running
  ansible.builtin.service:
    name: grafana-server
    state: started
    enabled: true

- name: run grafana template
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    mode: '0644'
  notify: Restart grafana

- name: Datasource for grafana
  ansible.builtin.template:
    src: datasources.yaml
    dest: /etc/grafana/provisioning/datasources/datasources.yaml
    mode: '0644'
  notify: Restart grafana

- name: Dashboards for grafana
  ansible.builtin.template:
    src: dashboards.yaml
    dest: /etc/grafana/provisioning/dashboards/dashboards.yaml
    mode: '0644'
  notify: Restart grafana

- name: Dashboards for grafana
  ansible.builtin.copy:
    dest: /var/lib/grafana/dashboards/
    src: "{{ item }}"
    mode: '0644'
  loop: 
    - main.json
    - backups.json
    - syslog.json
  notify: Restart grafana

