{
 "title": "Main",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Agama on my domain",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \"items\" FROM \"agama-stats\" WHERE \"name\" = 'IlliaShyn-1.agamais.ttu.'"
    }
   ]
  },
  {
   "title": "influxdb_write_write_ok",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 5, "x": 8, "y": 0 },
   "targets": [
    { "expr": "influxdb_write_write_ok", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU on VM's",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_gc_cpu_fraction{job=\"linux\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count agama",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT COUNT(*) \nFROM \"agama-stats\""
    }
   ]
  },
  {
   "title": "MySQL commands global",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 3 },
   "targets": [
    {
     "expr": "mysql_global_status_commands_total{job=\"mysql\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "haproxy_up",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "haproxy_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "haproxy_server_up",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "haproxy_server_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "keepalived_vrrp_state",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "keepalived_vrrp_state", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "keepalived_up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "keepalived_up{job=\"keepalived\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx_up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_up{job=\"nginx\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx requests",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_http_requests_total{job=\"nginx\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "influxdb_exporter_stats_query_success",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "influxdb_exporter_stats_query_success",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "bindup",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bind_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MySQL status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_up{job=\"mysql\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "bind_resolver_queries_total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bind_resolver_queries_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "__auto" }
   ]
  }
 ]
}