{
 "title": "Main",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Bind quieries",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bind_resolver_queries_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU on VM's",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_gc_cpu_fraction{job=\"linux\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bind up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bind_up{job=\"bind9\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MySQL commands global",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "mysql_global_status_commands_total{job=\"mysql\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MySQL status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_up{job=\"mysql\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx_up",
   "type": "stat",
   "gridPos": { "h": 7, "w": 11, "x": 8, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Nginx requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "nginx_http_requests_total{job=\"nginx\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}