- name: install mysql
  ansible.builtin.apt:
    name: 
      - mysql-server
      - python3-pymysql
    state: present

- name: mysql service is started
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: true
     
- name: mysql override.cnf
  ansible.builtin.template:
    dest: /etc/mysql/mysql.conf.d/override.cnf
    src: override.cnf.j2
  notify: Restart MySQL

- name: create database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create directory
  ansible.builtin.file:
    path: /var/lib/prometheus
    state: directory
  
- name: MySQL user
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    host: "%"
    priv: "{{ mysql_database }}.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  notify: Restart MySQL
  no_log: true

- name: Install Mysql exporter
  ansible.builtin.apt:
    name: prometheus-mysqld-exporter
    state: present

- name: MySQL exporter user
  community.mysql.mysql_user:
    name: "{{ exporter_user }}"
    password: "{{ exporter_password }}"
    priv: "*.*:PROCESS,REPLICATION CLIENT,SELECT"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  notify: Restart MySQL
  no_log: true

- name: my.conf template
  ansible.builtin.template:
    src: .my.conf.j2
    dest: /var/lib/prometheus/.my.cnf
    mode: '0600'
    owner: prometheus
  no_log: true
  notify: 
    - Restart Exporter
    - sleep 10

- meta: flush_handlers

- name: mysql exporter is running
  ansible.builtin.service:
    name: prometheus-mysqld-exporter
    state: started
    enabled: yes
    