apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: e91a23c9-c251-4690-aea4-62cc21dcfb51
    url: http://prometheus:9090/prometheus
    editable: false

  - name: InfluxDB:latency
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: agamadb
  
  - name: InfluxDB:telegraf
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: telegraf
    