- name: Restart MySQL
  ansible.builtin.service: 
    name: mysql
    state: restarted

- name: sleep 10
  ansible.builtin.command:
    cmd: sleep 10

- name: Restart Exporter
  ansible.builtin.service: 
    name: prometheus-mysqld-exporter
    state: restarted

- name: Reset MySQL source
  community.mysql.mysql_replication:
    mode: "{{ item }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  loop:
    - stopreplica
    - resetprimary
  when: inventory_hostname == mysql_host


- name: Reset MySQL replica
  community.mysql.mysql_replication:
    mode: "{{ item }}"
    primary_host: "{{ mysql_host }}"
    primary_user: "{{ mysql_replication_user }}"
    primary_password: "{{ mysql_replication_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  loop:
    - stopreplica
    - changeprimary
    - resetreplica
    - startreplica
  when: inventory_hostname != mysql_host

- name: Cron restart
  ansible.builtin.service: 
    name: cron
    state: restarted  