- name: Intsall bind9
  ansible.builtin.apt:
    name: 
      - bind9
      - prometheus-bind-exporter
    state: present

- name: Make sure bind9 is running
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - named
    - prometheus-bind-exporter


- name: Configure conf.options
  ansible.builtin.template:
    src: named.conf.{{ item }}.j2
    dest: /etc/bind/named.conf.{{ item }}
  with_items: 
    - options
    - local
  notify: 
    - Restart bind
    - Restart bind-exporter

- name: Configure zone
  ansible.builtin.template:
    src: zone.j2
    dest: /var/cache/bind/db.agamais.ttu
    mode: '0644'
  notify: rndc reload bind9

