#- name: Ansible ping module
#  ansible.builtin.ping:


#- name: Create Roman/Juri users
#  ansible.builtin.user:
#    name: "{{ item }}"
#  loop:
#   - romankuchin
#   - hudolejev

#- name: Add Roman's and Juri's public keys
#  ansible.posix.authorized_key:
#    user: "{{ item }}"
#    state: present
#    key: https://github.com/{{ item }}.keys
#  loop:
#   - romankuchin
#   - hudolejev

- name: Update APT cache
  ansible.builtin.apt:
    cache_valid_time: 86400

- name: Install prometheus exporter
  ansible.builtin.apt:
    name: prometheus-node-exporter
    state: present

- name: Install CA certificates
  ansible.builtin.apt:
    name: ca-certificates>=20230311ubuntu0.20.04.1

- name: Syslog-telegraph template
  ansible.builtin.template:
    src: rsyslogtel.conf
    dest: /etc/rsyslog.d/rsyslog.conf
    mode: '0644'
  notify: Restart Rsyslog

- name: Backup user 
  ansible.builtin.user: 
    name: backup
    state: present
    home: /home/backup
    shell: /bin/bash
    generate_ssh_key: true
  become: yes

- name: Backup template
  ansible.builtin.template:
    src: backup_hosts.j2
    dest: /home/backup/.ssh/known_hosts
    owner: backup
    group: backup
    mode: '0700'

- name: Create restore directory
  ansible.builtin.file:
    state: directory
    path: /home/backup/restore
    owner: backup
    group: backup
    mode: 0755

- name: install Duplicity
  ansible.builtin.apt:
    name: duplicity
    state: present

