# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).
# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    scrape_interval: 5s
    scrape_timeout: 5s

    metrics_path: '/prometheus/metrics'

    static_configs:
      - targets: ["localhost:9090"]

  - job_name: linux
    static_configs:
      - targets: 
        - ns-1:9119
        - ns-2:9119
        - ns-3:9100

  - job_name: mysql
    static_configs:
      - targets:
        - mysql-1:9104
        - mysql-2:9104

  - job_name: bind9
    static_configs:
      - targets:
        - ns-1:9119
        - ns-2:9119
        - ns-3:9100


  - job_name: nginx
    static_configs:
      - targets:
        - www-1:9113
        - www-2:9113
        - www-3:9113


  - job_name: influx
    static_configs:
      - targets:
        - influxdb:9424

  - job_name: backups
    static_configs:
      - targets: 
        - backup:9111

  - job_name: keepalived
    static_configs:
      - targets: 
        - lb-1:9101
        - lb-2:9101

  - job_name: haproxy
    static_configs:
      - targets: 
        - lb-1:9165
        - lb-2:9165


